version: '3.8'

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt_zigbee
    image: koenkk/zigbee2mqtt
    hostname: zigbee
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /home/USER/zigbee2mqtt/zigbee:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0


  mosquitto:
    container_name: zigbee2mqtt_mqtt
    hostname: mqtt

    ports:
      - 1883:1883
    image: eclipse-mosquitto
    volumes:
      - /home/USER/zigbee2mqtt/mqtt/config:/mosquitto/config
      - /home/USER/zigbee2mqtt/mqtt/data:/mosquitto/data
      - /home/USER/zigbee2mqtt/mqtt/log:/mosquitto/log
    restart: unless-stopped
